(function () {
  const themeKey = "amyc-theme";
  const lightnessKey = "amyc-lightness";
  const customCssKey = "amyc-custom-css";
  const syncViewersKey = "amyc-sync-viewers";
  const storageEventName = "amyc:display-persistence-change";
  const defaultThemeId = "sand";
  const defaultLightness = 0;
  const root = document.documentElement;
  const scriptEl = document.currentScript;
  const metaTheme = document.querySelector('meta[name="theme-color"]');
  const publicRecordsFooterContact = "db@amyc.us";
  const publicRecordsFooterPrefix = "No claim to public records or data. Contact: ";
  const adjustableTokens = [
    "paper", "paper-2", "paper-3", "plain", "plain-soft", "page-paper", "page-line",
    "ink", "ink-2", "ink-3", "ink-4", "rule", "rule-2", "chrome", "chrome-ink",
    "chrome-rule", "chrome-accent", "accent", "accent-2", "link", "warn", "ok",
    "good-border", "good-bg", "warn-border", "warn-bg", "warn-ink", "bar-fill",
    "row-hover",
  ];
  let baseThemeTokens = {};
  let currentLightness = 0;
  // palettes:begin (generated by scripts/palettes.mjs)
  const themes = [
    {
      id: "crimson",
      name: "Crimson",
      note: "Crimson and blush",
      names: {
        lightest: "Petal",
        lighter: "Peony",
        base: "Crimson",
        darker: "Garnet",
        darkest: "Oxblood",
      },
      colors: ["#9b0d23", "#ffdcd9", "#a7001c", "#fffbfa"],
    },
    {
      id: "sand",
      name: "Sand",
      note: "Terracotta and turquoise",
      names: {
        lightest: "Sunlit Sand",
        lighter: "Dune",
        base: "Sand",
        darker: "Umber",
        darkest: "Burnt Umber",
      },
      colors: ["#833b00", "#fce0c2", "#824700", "#fffbf7"],
    },
    {
      id: "ember",
      name: "Imperial",
      note: "White, black, and gold",
      names: {
        lightest: "White Gold",
        lighter: "Champagne",
        base: "Imperial",
        darker: "Gilt",
        darkest: "Black Gold",
      },
      colors: ["#ffffff", "#e5e5e5", "#805c00", "#0a0a0a"],
    },
    {
      id: "cypress",
      name: "Cypress",
      note: "Forest and lime",
      names: {
        lightest: "Fern",
        lighter: "Grove",
        base: "Cypress",
        darker: "Old Growth",
        darkest: "Blackwood",
      },
      colors: ["#00451b", "#002f10", "#a3cf68", "#043e19"],
    },
    {
      id: "tidepool",
      name: "Tidepool",
      note: "Teal and coral",
      names: {
        lightest: "Seafoam",
        lighter: "Tideglass",
        base: "Tidepool",
        darker: "Kelp",
        darkest: "Deep Kelp",
      },
      colors: ["#006151", "#c3f1e4", "#00675a", "#f4fffb"],
    },
    {
      id: "mist",
      name: "Mist",
      note: "Bright aqua",
      names: {
        lightest: "Whiteout",
        lighter: "Sea Mist",
        base: "Mist",
        darker: "Harbor Fog",
        darkest: "Deep Fog",
      },
      colors: ["#5bd0e9", "#c0effa", "#00646d", "#f6fdff"],
    },
    {
      id: "glacier",
      name: "Glacier",
      note: "Icy cobalt",
      names: {
        lightest: "Snowcap",
        lighter: "Blue Ice",
        base: "Glacier",
        darker: "Crevasse",
        darkest: "Polar Night",
      },
      colors: ["#005494", "#d2e8ff", "#005e8c", "#f9fcff"],
    },
    {
      id: "ultramarine",
      name: "Ultramarine",
      note: "Ultramarine and amber",
      names: {
        lightest: "Porcelain",
        lighter: "Periwinkle",
        base: "Ultramarine",
        darker: "Lapis",
        darkest: "Abyss",
      },
      colors: ["#2522a6", "#dce4ff", "#4242bf", "#fbfcff"],
    },
    {
      id: "lilac",
      name: "Lilac",
      note: "Lavender and mint",
      names: {
        lightest: "Pale Lilac",
        lighter: "Wisteria",
        base: "Lilac",
        darker: "Mauve",
        darkest: "Night Plum",
      },
      colors: ["#b9a3e9", "#e8e0ff", "#5c37b8", "#fcfbff"],
    },
    {
      id: "starlight",
      name: "Starlight",
      note: "Violet night and gold",
      names: {
        lightest: "Daystar",
        lighter: "Moonrise",
        base: "Starlight",
        darker: "Midnight",
        darkest: "Black Violet",
      },
      colors: ["#46206e", "#2c1a43", "#e6b642", "#3b2656"],
    },
    {
      id: "orchid",
      name: "Orchid",
      note: "Magenta and lime",
      names: {
        lightest: "Bloom",
        lighter: "Mallow",
        base: "Orchid",
        darker: "Mulberry",
        darkest: "Aubergine",
      },
      colors: ["#7d2386", "#f7dbf9", "#832298", "#fffaff"],
    },
    {
      id: "rose",
      name: "Rose",
      note: "Rose and leaf green",
      names: {
        lightest: "Blush",
        lighter: "Rosewater",
        base: "Rose",
        darker: "Mauve Rose",
        darkest: "Dark Rose",
      },
      colors: ["#f0a6b7", "#ffdae2", "#a20050", "#fffafb"],
    },
  ];
  const themeMidpoints = {
    crimson: {
      light: {
        paper: "#fff3f2", "paper-2": "#ffe5e3", "paper-3": "#ffd4d1", plain: "#fffdfd", "plain-soft": "#fff7f7",
        "page-paper": "#fffefe", "page-line": "#ffc4c1", ink: "#2c1515", "ink-2": "#4d302f", "ink-3": "#6c4a48",
        "ink-4": "#a27f7e", rule: "#f2a29f", "rule-2": "#fbcfcd", chrome: "#a7182a", "chrome-rule": "#790c1b",
        "chrome-ink": "#fff7f7", "chrome-accent": "#ffd5db", accent: "#aa001d", "accent-2": "#b52f33", link: "#00549a",
        warn: "#aa3300", ok: "#107537", "good-border": "#82c791", "good-bg": "#e3fae7", "warn-border": "#e3b160",
        "warn-bg": "#fff2de", "warn-ink": "#7e470d", "bar-fill": "#c52a33", "row-hover": "#ffe5e3",
      },
      dark: {
        paper: "#570c13", "paper-2": "#49090f", "paper-3": "#6a141b", plain: "#5e1318", "plain-soft": "#510b12",
        "page-paper": "#61161b", "page-line": "#962f33", ink: "#fff2f1", "ink-2": "#f6d5d3", "ink-3": "#eabab7",
        "ink-4": "#b68381", rule: "#a8353a", "rule-2": "#7d2227", chrome: "#6e0013", "chrome-rule": "#9f1f2b",
        "chrome-ink": "#ffefee", "chrome-accent": "#ffc1cb", accent: "#ffa09a", "accent-2": "#ff847f", link: "#9eccff",
        warn: "#ff9d7f", ok: "#7fd994", "good-border": "#448c56", "good-bg": "#17351f", "warn-border": "#aa7d2d",
        "warn-bg": "#3c2a0d", "warn-ink": "#f9cc87", "bar-fill": "#ff847e", "row-hover": "#74181f",
      },
    },
    sand: {
      light: {
        paper: "#fff4e9", "paper-2": "#fde8d2", "paper-3": "#f8dabb", plain: "#fffdfb", "plain-soft": "#fff8f1",
        "page-paper": "#fffefd", "page-line": "#f3cda6", ink: "#281908", "ink-2": "#483520", "ink-3": "#664f37",
        "ink-4": "#9b856e", rule: "#e3af77", "rule-2": "#f2d6b9", chrome: "#904100", "chrome-rule": "#672c00",
        "chrome-ink": "#fff8f4", "chrome-accent": "#90f6f5", accent: "#844800", "accent-2": "#985300", link: "#006068",
        warn: "#aa3300", ok: "#107537", "good-border": "#82c791", "good-bg": "#e3fae7", "warn-border": "#e3b160",
        "warn-bg": "#fff2de", "warn-ink": "#7e470d", "bar-fill": "#a35900", "row-hover": "#fee8d1",
      },
      dark: {
        paper: "#432600", "paper-2": "#371f00", "paper-3": "#533000", plain: "#4a2b00", "plain-soft": "#3e2300",
        "page-paper": "#4d2d00", "page-line": "#7c4b00", ink: "#fbf4ed", "ink-2": "#ecdbc9", "ink-3": "#dbc2a9",
        "ink-4": "#a78d72", rule: "#8b5500", "rule-2": "#663d00", chrome: "#5b2600", "chrome-rule": "#8b3f00",
        "chrome-ink": "#fff0e8", "chrome-accent": "#61eded", accent: "#ffa659", "accent-2": "#f2943c", link: "#61dce9",
        warn: "#ff9d7f", ok: "#7fd994", "good-border": "#448c56", "good-bg": "#17351f", "warn-border": "#aa7d2d",
        "warn-bg": "#3c2a0d", "warn-ink": "#f9cc87", "bar-fill": "#f6922e", "row-hover": "#5b3600",
      },
    },
    ember: {
      light: {
        paper: "#f6f6f6", "paper-2": "#ececec", "paper-3": "#dfdfdf", plain: "#fdfdfd", "plain-soft": "#f9f9f9",
        "page-paper": "#fefefe", "page-line": "#f4c761", ink: "#1d1d1d", "ink-2": "#393939", "ink-3": "#545454",
        "ink-4": "#898989", rule: "#c2982a", "rule-2": "#e9be57", chrome: "#ffffff", "chrome-rule": "#c2982a",
        "chrome-ink": "#1b1b1b", "chrome-accent": "#876200", accent: "#805c00", "accent-2": "#765400", link: "#725200",
        warn: "#aa3300", ok: "#107537", "good-border": "#82c791", "good-bg": "#e3fae7", "warn-border": "#e3b160",
        "warn-bg": "#fff2de", "warn-ink": "#7e470d", "bar-fill": "#966c00", "row-hover": "#ececec",
      },
      dark: {
        paper: "#1f1f1f", "paper-2": "#171717", "paper-3": "#2a2a2a", plain: "#242424", "plain-soft": "#1c1c1c",
        "page-paper": "#262626", "page-line": "#7f5d00", ink: "#e1e1e1", "ink-2": "#cacaca", "ink-3": "#b4b4b4",
        "ink-4": "#808080", rule: "#b78a16", "rule-2": "#866200", chrome: "#090909", "chrome-rule": "#a37800",
        "chrome-ink": "#f2f2f2", "chrome-accent": "#f9c647", accent: "#f2bf3f", "accent-2": "#e8b631", link: "#ffd166",
        warn: "#ff9d7f", ok: "#7fd994", "good-border": "#448c56", "good-bg": "#17351f", "warn-border": "#aa7d2d",
        "warn-bg": "#3c2a0d", "warn-ink": "#f9cc87", "bar-fill": "#e8b631", "row-hover": "#303030",
      },
    },
    cypress: {
      light: {
        paper: "#e7f9ea", "paper-2": "#d2f0d7", "paper-3": "#bde6c4", plain: "#f8fef9", "plain-soft": "#effcf1",
        "page-paper": "#fbfffb", "page-line": "#aee0b7", ink: "#102414", "ink-2": "#29412e", "ink-3": "#415d46",
        "ink-4": "#758f79", rule: "#81c790", "rule-2": "#bde2c3", chrome: "#00672c", "chrome-rule": "#00471d",
        "chrome-ink": "#f1faf2", "chrome-accent": "#d1e899", accent: "#446400", "accent-2": "#507400", link: "#00605c",
        warn: "#a83300", ok: "#0e7436", "good-border": "#7ec68d", "good-bg": "#e0f9e4", "warn-border": "#e2ae5a",
        "warn-bg": "#fff0da", "warn-ink": "#7d460c", "bar-fill": "#557b00", "row-hover": "#d7f3db",
      },
      dark: {
        paper: "#002f10", "paper-2": "#00250b", "paper-3": "#003c17", plain: "#013514", "plain-soft": "#002b0e",
        "page-paper": "#033816", "page-line": "#175f2f", ink: "#f0f7f1", "ink-2": "#d1e4d4", "ink-3": "#b3ceb7",
        "ink-4": "#7a987f", rule: "#1b6c36", "rule-2": "#0b4d23", chrome: "#003c17", "chrome-rule": "#006129",
        "chrome-ink": "#eaf7ec", "chrome-accent": "#c5df84", accent: "#a3cf64", "accent-2": "#92bf4f", link: "#64ded7",
        warn: "#ff9d7f", ok: "#7fd994", "good-border": "#458955", "good-bg": "#142e1a", "warn-border": "#a67b30",
        "warn-bg": "#342409", "warn-ink": "#f9cc87", "bar-fill": "#90c045", "row-hover": "#00431a",
      },
    },
    tidepool: {
      light: {
        paper: "#e8fbf5", "paper-2": "#d3f4eb", "paper-3": "#bcecde", plain: "#f9fffd", "plain-soft": "#f0fdf9",
        "page-paper": "#fcfffe", "page-line": "#a6e4d3", ink: "#05231c", "ink-2": "#1f4138", "ink-3": "#365d53",
        "ink-4": "#6e9288", rule: "#72cfb8", "rule-2": "#bae7da", chrome: "#006b59", "chrome-rule": "#004b3e",
        "chrome-ink": "#f0fcf9", "chrome-accent": "#ffd7cb", accent: "#00685b", "accent-2": "#007969", link: "#005a86",
        warn: "#aa3300", ok: "#107537", "good-border": "#82c791", "good-bg": "#e3fae7", "warn-border": "#e3b160",
        "warn-bg": "#fff2de", "warn-ink": "#7e470d", "bar-fill": "#008171", "row-hover": "#d2f5eb",
      },
      dark: {
        paper: "#00372d", "paper-2": "#002d24", "paper-3": "#004438", plain: "#003d32", "plain-soft": "#003329",
        "page-paper": "#003f34", "page-line": "#006756", ink: "#ecf8f5", "ink-2": "#c7e6dd", "ink-3": "#a5d3c6",
        "ink-4": "#6c9e91", rule: "#007461", "rule-2": "#005546", chrome: "#004237", "chrome-rule": "#006756",
        "chrome-ink": "#e4f9f3", "chrome-accent": "#ffc5b3", accent: "#23dbc1", "accent-2": "#00c9b1", link: "#8dd0ff",
        warn: "#ff9d7f", ok: "#7fd994", "good-border": "#448c56", "good-bg": "#17351f", "warn-border": "#aa7d2d",
        "warn-bg": "#3c2a0d", "warn-ink": "#f9cc87", "bar-fill": "#00c9b1", "row-hover": "#004b3e",
      },
    },
    mist: {
      light: {
        paper: "#e7faff", "paper-2": "#d1f3fb", "paper-3": "#b8e9f5", plain: "#fbfeff", "plain-soft": "#f0fcff",
        "page-paper": "#fdffff", "page-line": "#a1e1f0", ink: "#032128", "ink-2": "#1c3f47", "ink-3": "#335b64",
        "ink-4": "#6c9099", rule: "#6bcbe0", "rule-2": "#b7e5f0", chrome: "#62d6f0", "chrome-rule": "#2aa9c2",
        "chrome-ink": "#00242b", "chrome-accent": "#005860", accent: "#00666e", "accent-2": "#00767f", link: "#4744a4",
        warn: "#aa3300", ok: "#107537", "good-border": "#82c791", "good-bg": "#e3fae7", "warn-border": "#e3b160",
        "warn-bg": "#fff2de", "warn-ink": "#7e470d", "bar-fill": "#007e88", "row-hover": "#d0f3fc",
      },
      dark: {
        paper: "#004551", "paper-2": "#003b46", "paper-3": "#005360", plain: "#004b58", "plain-soft": "#00414c",
        "page-paper": "#014e5b", "page-line": "#0f7688", ink: "#eef7f9", "ink-2": "#cde3e8", "ink-3": "#aeced6",
        "ink-4": "#7799a1", rule: "#007082", "rule-2": "#036373", chrome: "#00515f", "chrome-rule": "#007689",
        "chrome-ink": "#e8f7fa", "chrome-accent": "#72eed0", accent: "#00d6e7", "accent-2": "#00c5d4", link: "#bcc2ff",
        warn: "#ff9d7f", ok: "#7fd994", "good-border": "#448c56", "good-bg": "#17351f", "warn-border": "#aa7d2d",
        "warn-bg": "#3c2a0d", "warn-ink": "#f9cc87", "bar-fill": "#00c5d4", "row-hover": "#005a69",
      },
    },
    glacier: {
      light: {
        paper: "#f0f7ff", "paper-2": "#deeeff", "paper-3": "#c8e3ff", plain: "#fcfeff", "plain-soft": "#f5faff",
        "page-paper": "#fefeff", "page-line": "#b5d9ff", ink: "#0e1e2e", "ink-2": "#283b4f", "ink-3": "#40566e",
        "ink-4": "#768ca2", rule: "#8bbff6", "rule-2": "#c3dffc", chrome: "#005da2", "chrome-rule": "#004174",
        "chrome-ink": "#f5faff", "chrome-accent": "#91f4ff", accent: "#00608e", "accent-2": "#006fa4", link: "#214ea5",
        warn: "#aa3300", ok: "#107537", "good-border": "#82c791", "good-bg": "#e3fae7", "warn-border": "#e3b160",
        "warn-bg": "#fff2de", "warn-ink": "#7e470d", "bar-fill": "#0076af", "row-hover": "#deeeff",
      },
      dark: {
        paper: "#002f56", "paper-2": "#002648", "paper-3": "#003a69", plain: "#00345f", "plain-soft": "#002b50",
        "page-paper": "#003763", "page-line": "#075a9b", ink: "#eef6fe", "ink-2": "#cde0f5", "ink-3": "#afcbe8",
        "ink-4": "#7895b5", rule: "#0865ae", "rule-2": "#004982", chrome: "#003967", "chrome-rule": "#005a9d",
        "chrome-ink": "#ebf5ff", "chrome-accent": "#61ebfa", accent: "#76c7ff", "accent-2": "#46b9ff", link: "#aac8ff",
        warn: "#ff9d7f", ok: "#7fd994", "good-border": "#448c56", "good-bg": "#17351f", "warn-border": "#aa7d2d",
        "warn-bg": "#3c2a0d", "warn-ink": "#f9cc87", "bar-fill": "#46b9ff", "row-hover": "#004174",
      },
    },
    ultramarine: {
      light: {
        paper: "#f3f6ff", "paper-2": "#e5ebff", "paper-3": "#d5dfff", plain: "#fdfdff", "plain-soft": "#f7f9ff",
        "page-paper": "#fefeff", "page-line": "#c6d3ff", ink: "#171c2f", "ink-2": "#313850", "ink-3": "#4a536f",
        "ink-4": "#8088a4", rule: "#a5b7f8", "rule-2": "#d0dafe", chrome: "#292aad", "chrome-rule": "#190085",
        "chrome-ink": "#f7f9ff", "chrome-accent": "#ffdab1", accent: "#4343c0", "accent-2": "#5157c6", link: "#683795",
        warn: "#aa3300", ok: "#107537", "good-border": "#82c791", "good-bg": "#e3fae7", "warn-border": "#e3b160",
        "warn-bg": "#fff2de", "warn-ink": "#7e470d", "bar-fill": "#555bda", "row-hover": "#e5ebff",
      },
      dark: {
        paper: "#1a2070", "paper-2": "#14195e", "paper-3": "#222986", plain: "#1e2676", "plain-soft": "#181d68",
        "page-paper": "#202979", "page-line": "#3a48b8", ink: "#f2f5ff", "ink-2": "#d2ddff", "ink-3": "#b7c5f7",
        "ink-4": "#818fc4", rule: "#4151ce", "rule-2": "#2d399c", chrome: "#210da0", "chrome-rule": "#3740c9",
        "chrome-ink": "#eff3ff", "chrome-accent": "#ffc98a", accent: "#acb8ff", "accent-2": "#98a6ff", link: "#d7b6ff",
        warn: "#ff9d7f", ok: "#7fd994", "good-border": "#448c56", "good-bg": "#17351f", "warn-border": "#aa7d2d",
        "warn-bg": "#3c2a0d", "warn-ink": "#f9cc87", "bar-fill": "#98a6ff", "row-hover": "#272f92",
      },
    },
    lilac: {
      light: {
        paper: "#f7f4ff", "paper-2": "#eee8ff", "paper-3": "#e3d9ff", plain: "#fefdff", "plain-soft": "#faf8ff",
        "page-paper": "#fefeff", "page-line": "#daccfc", ink: "#1f192c", "ink-2": "#3c344d", "ink-3": "#574e6b",
        "ink-4": "#8c84a0", rule: "#c2aef0", "rule-2": "#dfd5f9", chrome: "#bfaaef", "chrome-rule": "#947fc1",
        "chrome-ink": "#231838", "chrome-accent": "#50349c", accent: "#5d39b9", "accent-2": "#6a4fc0", link: "#314aa6",
        warn: "#aa3300", ok: "#107537", "good-border": "#82c791", "good-bg": "#e3fae7", "warn-border": "#e3b160",
        "warn-bg": "#fff2de", "warn-ink": "#7e470d", "bar-fill": "#7151d3", "row-hover": "#eee8ff",
      },
      dark: {
        paper: "#3f315b", "paper-2": "#362a4e", "paper-3": "#4c3c6c", plain: "#453761", "plain-soft": "#3b2e55",
        "page-paper": "#473964", "page-line": "#6d5a95", ink: "#f6f4fb", "ink-2": "#e0dbed", "ink-3": "#cac2de",
        "ink-4": "#958da9", rule: "#6b5595", "rule-2": "#5b4a7e", chrome: "#4d3577", "chrome-rule": "#6e569d",
        "chrome-ink": "#f5f1fe", "chrome-accent": "#85edbc", accent: "#bcb2ff", "accent-2": "#ad9eff", link: "#b0c6ff",
        warn: "#ff9d7f", ok: "#7fd994", "good-border": "#448c56", "good-bg": "#17351f", "warn-border": "#aa7d2d",
        "warn-bg": "#3c2a0d", "warn-ink": "#f9cc87", "bar-fill": "#ad9eff", "row-hover": "#534275",
      },
    },
    starlight: {
      light: {
        paper: "#f6f1ff", "paper-2": "#ece1ff", "paper-3": "#e1d1fe", plain: "#fdfcff", "plain-soft": "#f9f6ff",
        "page-paper": "#fefdff", "page-line": "#dac6fb", ink: "#221a2e", "ink-2": "#3e354e", "ink-3": "#5a4e6c",
        "ink-4": "#8c819e", rule: "#c0a4ec", "rule-2": "#ddcef6", chrome: "#6833a2", "chrome-rule": "#482172",
        "chrome-ink": "#f9f6ff", "chrome-accent": "#fad989", accent: "#705400", "accent-2": "#7748b7", link: "#006060",
        warn: "#a83300", ok: "#0e7436", "good-border": "#7ec68d", "good-bg": "#e0f9e4", "warn-border": "#e2ae5a",
        "warn-bg": "#fff0da", "warn-ink": "#7d460c", "bar-fill": "#896700", "row-hover": "#eee5ff",
      },
      dark: {
        paper: "#2d1a45", "paper-2": "#241437", "paper-3": "#3a2455", plain: "#321f4b", "plain-soft": "#29183f",
        "page-paper": "#35224d", "page-line": "#5b407f", ink: "#f6f3fb", "ink-2": "#e1daef", "ink-3": "#cbc0de",
        "ink-4": "#9588a9", rule: "#674990", "rule-2": "#493169", chrome: "#3d1a61", "chrome-rule": "#5d3b88",
        "chrome-ink": "#f5f0fe", "chrome-accent": "#f3ce71", accent: "#e7b63b", "accent-2": "#bd96fe", link: "#62dedd",
        warn: "#ff9d7f", ok: "#7fd994", "good-border": "#458955", "good-bg": "#142e1a", "warn-border": "#a67b30",
        "warn-bg": "#342409", "warn-ink": "#f9cc87", "bar-fill": "#d9a500", "row-hover": "#40295e",
      },
    },
    orchid: {
      light: {
        paper: "#fef2fe", "paper-2": "#f9e4fa", "paper-3": "#f2d4f4", plain: "#fffcff", "plain-soft": "#fff6ff",
        "page-paper": "#fffeff", "page-line": "#ecc7ef", ink: "#261727", "ink-2": "#443246", "ink-3": "#614b63",
        "ink-4": "#968198", rule: "#d9a6dd", "rule-2": "#edd1ef", chrome: "#872b91", "chrome-rule": "#611b68",
        "chrome-ink": "#fef6ff", "chrome-accent": "#dbeaa2", accent: "#852499", "accent-2": "#903ea3", link: "#2a4ca6",
        warn: "#aa3300", ok: "#107537", "good-border": "#82c791", "good-bg": "#e3fae7", "warn-border": "#e3b160",
        "warn-bg": "#fff2de", "warn-ink": "#7e470d", "bar-fill": "#9d3eb1", "row-hover": "#fae4fb",
      },
      dark: {
        paper: "#47134c", "paper-2": "#3b0e3f", "paper-3": "#561b5c", plain: "#4d1952", "plain-soft": "#421146",
        "page-paper": "#4f1c55", "page-line": "#7d3684", ink: "#fbf2fb", "ink-2": "#ecd6ed", "ink-3": "#dbbbdd",
        "ink-4": "#a685a9", rule: "#8c3d94", "rule-2": "#68296e", chrome: "#5c0065", "chrome-rule": "#832b8c",
        "chrome-ink": "#fdeefe", "chrome-accent": "#cddf82", accent: "#e59ff6", "accent-2": "#d78de8", link: "#adc7ff",
        warn: "#ff9d7f", ok: "#7fd994", "good-border": "#448c56", "good-bg": "#17351f", "warn-border": "#aa7d2d",
        "warn-bg": "#3c2a0d", "warn-ink": "#f9cc87", "bar-fill": "#da8aec", "row-hover": "#5f2065",
      },
    },
    rose: {
      light: {
        paper: "#fff2f5", "paper-2": "#ffe4e9", "paper-3": "#ffd2dc", plain: "#fffdfd", "plain-soft": "#fff7f9",
        "page-paper": "#fffefe", "page-line": "#fdc3d0", ink: "#2c151b", "ink-2": "#4c3037", "ink-3": "#6b4951",
        "ink-4": "#a07f86", rule: "#efa1b3", "rule-2": "#faced8", chrome: "#f7acbd", "chrome-rule": "#c88192",
        "chrome-ink": "#36111c", "chrome-accent": "#8c0e46", accent: "#a40051", "accent-2": "#b02e60", link: "#006537",
        warn: "#aa3300", ok: "#107537", "good-border": "#82c791", "good-bg": "#e3fae7", "warn-border": "#e3b160",
        "warn-bg": "#fff2de", "warn-ink": "#7e470d", "bar-fill": "#bf2966", "row-hover": "#ffe4e9",
      },
      dark: {
        paper: "#5a2d39", "paper-2": "#4d2630", "paper-3": "#6b3644", plain: "#60323e", "plain-soft": "#542a35",
        "page-paper": "#633541", "page-line": "#935263", ink: "#fbf3f4", "ink-2": "#edd8dc", "ink-3": "#ddbec4",
        "ink-4": "#a8888f", rule: "#904a5d", "rule-2": "#7d4453", chrome: "#732b41", "chrome-rule": "#994d62",
        "chrome-ink": "#feeff2", "chrome-accent": "#ffc898", accent: "#ff9bb7", "accent-2": "#fa82a6", link: "#8bdda8",
        warn: "#ff9d7f", ok: "#7fd994", "good-border": "#448c56", "good-bg": "#17351f", "warn-border": "#aa7d2d",
        "warn-bg": "#3c2a0d", "warn-ink": "#f9cc87", "bar-fill": "#fe7ea6", "row-hover": "#743c4b",
      },
    },
  };
  const themeVariants = {
    crimson: {
      light: {
        paper: "#fff8f7", "paper-2": "#ffeeed", "paper-3": "#ffdfdd", plain: "#ffffff", "plain-soft": "#fffbfa",
        "page-paper": "#ffffff", "page-line": "#fdcdca", ink: "#291413", "ink-2": "#4b302f", "ink-3": "#694947",
        "ink-4": "#a38381", rule: "#f4b0ad", "rule-2": "#fdd9d7", chrome: "#b32130", "chrome-rule": "#86101f",
        "chrome-ink": "#fffbfa", "chrome-accent": "#ffdee3", accent: "#ac001e", "accent-2": "#b63135", link: "#00569d",
        warn: "#ac3400", ok: "#137738", "good-border": "#88ca95", "good-bg": "#e8fbeb", "warn-border": "#e5b568",
        "warn-bg": "#fff4e4", "warn-ink": "#804810", "bar-fill": "#c92f36", "row-hover": "#ffe8e7",
      },
      dark: {
        paper: "#3e0409", "paper-2": "#300206", "paper-3": "#4f0910", plain: "#45080d", "plain-soft": "#380308",
        "page-paper": "#480b10", "page-line": "#7d2227", ink: "#fef2f1", "ink-2": "#f5d6d4", "ink-3": "#e4b7b5",
        "ink-4": "#af7d7b", rule: "#8f282e", "rule-2": "#66161c", chrome: "#53000c", "chrome-rule": "#86101f",
        "chrome-ink": "#ffedec", "chrome-accent": "#ffbcc7", accent: "#ffa09a", "accent-2": "#ff847f", link: "#9eccff",
        warn: "#ff9d7f", ok: "#7fd994", "good-border": "#458554", "good-bg": "#102816", "warn-border": "#a17833",
        "warn-bg": "#2d1f05", "warn-ink": "#f9cc87", "bar-fill": "#ff847e", "row-hover": "#570c13",
      },
    },
    sand: {
      light: {
        paper: "#fff9f2", "paper-2": "#fef0e2", "paper-3": "#fae4ce", plain: "#ffffff", "plain-soft": "#fffbf7",
        "page-paper": "#ffffff", "page-line": "#f4d5b5", ink: "#251707", "ink-2": "#463421", "ink-3": "#634e37",
        "ink-4": "#9d8873", rule: "#e7bb8c", "rule-2": "#f5dfc7", chrome: "#9c4700", "chrome-rule": "#733200",
        "chrome-ink": "#fffbf9", "chrome-accent": "#a7f9f8", accent: "#864900", "accent-2": "#9a5500", link: "#006169",
        warn: "#ac3400", ok: "#137738", "good-border": "#88ca95", "good-bg": "#e8fbeb", "warn-border": "#e5b568",
        "warn-bg": "#fff4e4", "warn-ink": "#804810", "bar-fill": "#a75c00", "row-hover": "#fdebd8",
      },
      dark: {
        paper: "#2e1800", "paper-2": "#231100", "paper-3": "#3c2200", plain: "#341d00", "plain-soft": "#291500",
        "page-paper": "#371f00", "page-line": "#663d00", ink: "#faf4ee", "ink-2": "#ebdbcb", "ink-3": "#d7c0a8",
        "ink-4": "#a1876c", rule: "#754600", "rule-2": "#512f00", chrome: "#451b00", "chrome-rule": "#733200",
        "chrome-ink": "#feeee6", "chrome-accent": "#5de9e9", accent: "#ffa658", "accent-2": "#f2943c", link: "#61dce9",
        warn: "#ff9d7f", ok: "#7fd994", "good-border": "#458554", "good-bg": "#102816", "warn-border": "#a17833",
        "warn-bg": "#2d1f05", "warn-ink": "#f9cc87", "bar-fill": "#f6922e", "row-hover": "#432600",
      },
    },
    ember: {
      light: {
        paper: "#fafafa", "paper-2": "#f2f2f2", "paper-3": "#e8e8e8", plain: "#ffffff", "plain-soft": "#fcfcfc",
        "page-paper": "#ffffff", "page-line": "#f4c761", ink: "#1b1b1b", "ink-2": "#383838", "ink-3": "#525252",
        "ink-4": "#8c8c8c", rule: "#c2982a", "rule-2": "#e9be57", chrome: "#ffffff", "chrome-rule": "#c2982a",
        "chrome-ink": "#1b1b1b", "chrome-accent": "#876200", accent: "#805c00", "accent-2": "#765400", link: "#725200",
        warn: "#ac3400", ok: "#137738", "good-border": "#88ca95", "good-bg": "#e8fbeb", "warn-border": "#e5b568",
        "warn-bg": "#fff4e4", "warn-ink": "#804810", "bar-fill": "#966c00", "row-hover": "#eeeeee",
      },
      dark: {
        paper: "#0a0a0a", "paper-2": "#040404", "paper-3": "#141414", plain: "#0e0e0e", "plain-soft": "#070707",
        "page-paper": "#101010", "page-line": "#7f5d00", ink: "#d7d7d7", "ink-2": "#c1c1c1", "ink-3": "#a8a8a8",
        "ink-4": "#717171", rule: "#b78a16", "rule-2": "#866200", chrome: "#000000", "chrome-rule": "#a37800",
        "chrome-ink": "#f2f2f2", "chrome-accent": "#f9c647", accent: "#f2bf3f", "accent-2": "#e8b631", link: "#ffd166",
        warn: "#ff9d7f", ok: "#7fd994", "good-border": "#458554", "good-bg": "#102816", "warn-border": "#a17833",
        "warn-bg": "#2d1f05", "warn-ink": "#f9cc87", "bar-fill": "#e8b631", "row-hover": "#181818",
      },
    },
    cypress: {
      light: {
        paper: "#edfaef", "paper-2": "#dbf3df", "paper-3": "#c8eacd", plain: "#fbfffb", "plain-soft": "#f3fdf4",
        "page-paper": "#fcfffd", "page-line": "#b6e2be", ink: "#0f2213", "ink-2": "#29402d", "ink-3": "#415c46",
        "ink-4": "#77917c", rule: "#8ecc9a", "rule-2": "#c5e5ca", chrome: "#006e30", "chrome-rule": "#004e20",
        "chrome-ink": "#f3fcf5", "chrome-accent": "#d6eca5", accent: "#456500", "accent-2": "#517500", link: "#00615d",
        warn: "#aa3300", ok: "#107537", "good-border": "#82c791", "good-bg": "#e3fae7", "warn-border": "#e3b160",
        "warn-bg": "#fff2de", "warn-ink": "#7e470d", "bar-fill": "#567d00", "row-hover": "#dbf4df",
      },
      dark: {
        paper: "#00260c", "paper-2": "#001d07", "paper-3": "#003312", plain: "#002c0f", "plain-soft": "#00220a",
        "page-paper": "#012e11", "page-line": "#115629", ink: "#f1f7f2", "ink-2": "#d2e4d4", "ink-3": "#b2ccb6",
        "ink-4": "#77957c", rule: "#15632f", "rule-2": "#05441d", chrome: "#003312", "chrome-rule": "#005724",
        "chrome-ink": "#e9f6eb", "chrome-accent": "#c4de83", accent: "#a2d060", "accent-2": "#92bf4f", link: "#64ded7",
        warn: "#ff9d7f", ok: "#7fd994", "good-border": "#458554", "good-bg": "#102816", "warn-border": "#a17833",
        "warn-bg": "#2d1f05", "warn-ink": "#f9cc87", "bar-fill": "#90c045", "row-hover": "#003915",
      },
    },
    tidepool: {
      light: {
        paper: "#f2fdf9", "paper-2": "#e3f8f2", "paper-3": "#cff1e7", plain: "#ffffff", "plain-soft": "#f7fefb",
        "page-paper": "#ffffff", "page-line": "#b5e7d9", ink: "#05201a", "ink-2": "#1f3f37", "ink-3": "#365b51",
        "ink-4": "#73948b", rule: "#8ad6c2", "rule-2": "#c8ece2", chrome: "#007461", "chrome-rule": "#005546",
        "chrome-ink": "#f4fffb", "chrome-accent": "#ffe0d7", accent: "#006a5d", "accent-2": "#007a6b", link: "#005b88",
        warn: "#ac3400", ok: "#137738", "good-border": "#88ca95", "good-bg": "#e8fbeb", "warn-border": "#e5b568",
        "warn-bg": "#fff4e4", "warn-ink": "#804810", "bar-fill": "#008474", "row-hover": "#d9f6ee",
      },
      dark: {
        paper: "#00251d", "paper-2": "#001b15", "paper-3": "#003128", plain: "#002a22", "plain-soft": "#00211a",
        "page-paper": "#002d24", "page-line": "#005546", ink: "#eef8f5", "ink-2": "#c9e5dd", "ink-3": "#a4cfc3",
        "ink-4": "#66988b", rule: "#006151", "rule-2": "#004237", chrome: "#003128", "chrome-rule": "#005546",
        "chrome-ink": "#e3f7f1", "chrome-accent": "#ffc0ac", accent: "#00dbc1", "accent-2": "#00c9b1", link: "#8dd0ff",
        warn: "#ff9d7f", ok: "#7fd994", "good-border": "#458554", "good-bg": "#102816", "warn-border": "#a17833",
        "warn-bg": "#2d1f05", "warn-ink": "#f9cc87", "bar-fill": "#00c9b1", "row-hover": "#00372d",
      },
    },
    mist: {
      light: {
        paper: "#f1fcff", "paper-2": "#e1f7fc", "paper-3": "#cceff8", plain: "#ffffff", "plain-soft": "#f6fdff",
        "page-paper": "#ffffff", "page-line": "#b2e5f1", ink: "#031f24", "ink-2": "#1d3d45", "ink-3": "#345962",
        "ink-4": "#71939b", rule: "#85d2e4", "rule-2": "#c6eaf3", chrome: "#69ddf6", "chrome-rule": "#33b0c8",
        "chrome-ink": "#00242b", "chrome-accent": "#005860", accent: "#006770", "accent-2": "#007781", link: "#4845a5",
        warn: "#ac3400", ok: "#137738", "good-border": "#88ca95", "good-bg": "#e8fbeb", "warn-border": "#e5b568",
        "warn-bg": "#fff4e4", "warn-ink": "#804810", "bar-fill": "#00818c", "row-hover": "#d7f5fc",
      },
      dark: {
        paper: "#00333c", "paper-2": "#002932", "paper-3": "#00404b", plain: "#003943", "plain-soft": "#002f38",
        "page-paper": "#003b46", "page-line": "#036373", ink: "#eff7f8", "ink-2": "#cee2e7", "ink-3": "#accad1",
        "ink-4": "#71939b", rule: "#007082", "rule-2": "#00515f", chrome: "#00404b", "chrome-rule": "#006373",
        "chrome-ink": "#e6f5f8", "chrome-accent": "#6febcc", accent: "#00d6e7", "accent-2": "#00c5d4", link: "#bcc2ff",
        warn: "#ff9d7f", ok: "#7fd994", "good-border": "#458554", "good-bg": "#102816", "warn-border": "#a17833",
        "warn-bg": "#2d1f05", "warn-ink": "#f9cc87", "bar-fill": "#00c5d4", "row-hover": "#004551",
      },
    },
    glacier: {
      light: {
        paper: "#f6faff", "paper-2": "#e9f4ff", "paper-3": "#d7eaff", plain: "#ffffff", "plain-soft": "#f9fcff",
        "page-paper": "#ffffff", "page-line": "#c0deff", ink: "#0d1c2a", "ink-2": "#283a4c", "ink-3": "#3f556b",
        "ink-4": "#7a8fa4", rule: "#9dc9f7", "rule-2": "#d0e6fd", chrome: "#0065b0", "chrome-rule": "#004982",
        "chrome-ink": "#f9fcff", "chrome-accent": "#aef7ff", accent: "#006191", "accent-2": "#0070a6", link: "#224fa7",
        warn: "#ac3400", ok: "#137738", "good-border": "#88ca95", "good-bg": "#e8fbeb", "warn-border": "#e5b568",
        "warn-bg": "#fff4e4", "warn-ink": "#804810", "bar-fill": "#0079b3", "row-hover": "#e2f0ff",
      },
      dark: {
        paper: "#001f3c", "paper-2": "#00172f", "paper-3": "#002a4e", plain: "#002444", "plain-soft": "#001b36",
        "page-paper": "#002648", "page-line": "#004982", ink: "#eff6fd", "ink-2": "#cfe0f3", "ink-3": "#adc7e3",
        "ink-4": "#728fae", rule: "#005494", "rule-2": "#003967", chrome: "#002a4e", "chrome-rule": "#004982",
        "chrome-ink": "#e8f3ff", "chrome-accent": "#5de8f6", accent: "#76c7ff", "accent-2": "#46b9ff", link: "#aac8ff",
        warn: "#ff9d7f", ok: "#7fd994", "good-border": "#458554", "good-bg": "#102816", "warn-border": "#a17833",
        "warn-bg": "#2d1f05", "warn-ink": "#f9cc87", "bar-fill": "#46b9ff", "row-hover": "#002f56",
      },
    },
    ultramarine: {
      light: {
        paper: "#f8faff", "paper-2": "#eef2ff", "paper-3": "#e0e7ff", plain: "#ffffff", "plain-soft": "#fbfcff",
        "page-paper": "#ffffff", "page-line": "#ced9ff", ink: "#15192b", "ink-2": "#31374d", "ink-3": "#4a516c",
        "ink-4": "#838ba5", rule: "#b2c2f9", "rule-2": "#d9e2fe", chrome: "#2d31b4", "chrome-rule": "#1c0092",
        "chrome-ink": "#fbfcff", "chrome-accent": "#ffe3c3", accent: "#4445c2", "accent-2": "#5259c8", link: "#693996",
        warn: "#ac3400", ok: "#137738", "good-border": "#88ca95", "good-bg": "#e8fbeb", "warn-border": "#e5b568",
        "warn-bg": "#fff4e4", "warn-ink": "#804810", "bar-fill": "#585edd", "row-hover": "#e9eeff",
      },
      dark: {
        paper: "#0f1251", "paper-2": "#0a0c40", "paper-3": "#171b66", plain: "#131759", "plain-soft": "#0d1049",
        "page-paper": "#151a5c", "page-line": "#2d399c", ink: "#f2f5ff", "ink-2": "#d3ddfd", "ink-3": "#b5c2f1",
        "ink-4": "#7b89bd", rule: "#3542b1", "rule-2": "#222a81", chrome: "#17047d", "chrome-rule": "#2b30ac",
        "chrome-ink": "#edf1ff", "chrome-accent": "#ffc580", accent: "#acb8ff", "accent-2": "#98a6ff", link: "#d7b6ff",
        warn: "#ff9d7f", ok: "#7fd994", "good-border": "#458554", "good-bg": "#102816", "warn-border": "#a17833",
        "warn-bg": "#2d1f05", "warn-ink": "#f9cc87", "bar-fill": "#98a6ff", "row-hover": "#1a2070",
      },
    },
    lilac: {
      light: {
        paper: "#faf9ff", "paper-2": "#f4f0ff", "paper-3": "#eae3ff", plain: "#ffffff", "plain-soft": "#fcfbff",
        "page-paper": "#ffffff", "page-line": "#dfd4fb", ink: "#1d1729", "ink-2": "#3a344a", "ink-3": "#554d68",
        "ink-4": "#8f87a2", rule: "#cab9f2", "rule-2": "#e6defb", chrome: "#c5b0f6", "chrome-rule": "#9a85c8",
        "chrome-ink": "#231838", "chrome-accent": "#50349c", accent: "#5f3bbb", "accent-2": "#6b50c2", link: "#324ca7",
        warn: "#ac3400", ok: "#137738", "good-border": "#88ca95", "good-bg": "#e8fbeb", "warn-border": "#e5b568",
        "warn-bg": "#fff4e4", "warn-ink": "#804810", "bar-fill": "#7454d6", "row-hover": "#f0ebff",
      },
      dark: {
        paper: "#2e2344", "paper-2": "#251c37", "paper-3": "#3a2d54", plain: "#33284a", "plain-soft": "#2a203e",
        "page-paper": "#352a4c", "page-line": "#5b4a7e", ink: "#f6f4fa", "ink-2": "#e0dbec", "ink-3": "#c6c0d9",
        "ink-4": "#8f87a3", rule: "#67548e", "rule-2": "#4a3b68", chrome: "#3c285e", "chrome-rule": "#5d4786",
        "chrome-ink": "#f3f0fc", "chrome-accent": "#82eab9", accent: "#bcb2ff", "accent-2": "#ad9eff", link: "#b0c6ff",
        warn: "#ff9d7f", ok: "#7fd994", "good-border": "#458554", "good-bg": "#102816", "warn-border": "#a17833",
        "warn-bg": "#2d1f05", "warn-ink": "#f9cc87", "bar-fill": "#ad9eff", "row-hover": "#3f315b",
      },
    },
    starlight: {
      light: {
        paper: "#f8f4ff", "paper-2": "#f0e7ff", "paper-3": "#e6d8fe", plain: "#fefdff", "plain-soft": "#faf8ff",
        "page-paper": "#fefeff", "page-line": "#ddcbfb", ink: "#20182c", "ink-2": "#3d344c", "ink-3": "#594e6a",
        "ink-4": "#8e839f", rule: "#c6acee", "rule-2": "#e1d4f8", chrome: "#6f38aa", "chrome-rule": "#4f257b",
        "chrome-ink": "#faf8ff", "chrome-accent": "#fcde97", accent: "#715500", "accent-2": "#7849b9", link: "#006161",
        warn: "#aa3300", ok: "#107537", "good-border": "#82c791", "good-bg": "#e3fae7", "warn-border": "#e3b160",
        "warn-bg": "#fff2de", "warn-ink": "#7e470d", "bar-fill": "#8b6900", "row-hover": "#f0e7ff",
      },
      dark: {
        paper: "#251439", "paper-2": "#1b0e2c", "paper-3": "#311d49", plain: "#2a183f", "plain-soft": "#201133",
        "page-paper": "#2c1b42", "page-line": "#523874", ink: "#f6f4fb", "ink-2": "#e1daee", "ink-3": "#c9bedb",
        "ink-4": "#9285a6", rule: "#5e4184", "rule-2": "#412a5e", chrome: "#341555", "chrome-rule": "#54347c",
        "chrome-ink": "#f4effd", "chrome-accent": "#f2cd6f", accent: "#e8b631", "accent-2": "#bd96fe", link: "#62dedd",
        warn: "#ff9d7f", ok: "#7fd994", "good-border": "#458554", "good-bg": "#102816", "warn-border": "#a17833",
        "warn-bg": "#2d1f05", "warn-ink": "#f9cc87", "bar-fill": "#d9a500", "row-hover": "#362151",
      },
    },
    orchid: {
      light: {
        paper: "#fef7fe", "paper-2": "#fbedfc", "paper-3": "#f5e0f7", plain: "#ffffff", "plain-soft": "#fffaff",
        "page-paper": "#ffffff", "page-line": "#eecff0", ink: "#231524", "ink-2": "#423144", "ink-3": "#5f4a61",
        "ink-4": "#99849a", rule: "#deb3e2", "rule-2": "#f1daf2", chrome: "#92339b", "chrome-rule": "#6c2074",
        "chrome-ink": "#fffaff", "chrome-accent": "#e3f0b3", accent: "#86269b", "accent-2": "#9240a4", link: "#2b4ea7",
        warn: "#ac3400", ok: "#137738", "good-border": "#88ca95", "good-bg": "#e8fbeb", "warn-border": "#e5b568",
        "warn-bg": "#fff4e4", "warn-ink": "#804810", "bar-fill": "#a041b5", "row-hover": "#fae8fb",
      },
      dark: {
        paper: "#310936", "paper-2": "#260529", "paper-3": "#401045", plain: "#370d3b", "plain-soft": "#2c0730",
        "page-paper": "#3a103e", "page-line": "#68296e", ink: "#faf2fa", "ink-2": "#ebd6ec", "ink-3": "#d6b9d8",
        "ink-4": "#a07fa3", rule: "#77307e", "rule-2": "#541c59", chrome: "#45004c", "chrome-rule": "#6e1d76",
        "chrome-ink": "#fbecfc", "chrome-accent": "#cadc7f", accent: "#e89cf9", "accent-2": "#d78de8", link: "#adc7ff",
        warn: "#ff9d7f", ok: "#7fd994", "good-border": "#458554", "good-bg": "#102816", "warn-border": "#a17833",
        "warn-bg": "#2d1f05", "warn-ink": "#f9cc87", "bar-fill": "#da8aec", "row-hover": "#47134c",
      },
    },
    rose: {
      light: {
        paper: "#fff8f9", "paper-2": "#ffedf1", "paper-3": "#ffdee5", plain: "#ffffff", "plain-soft": "#fffafb",
        "page-paper": "#ffffff", "page-line": "#fcccd6", ink: "#281319", "ink-2": "#4a2f35", "ink-3": "#684850",
        "ink-4": "#a28289", rule: "#f1afbe", "rule-2": "#fcd9e0", chrome: "#fdb2c4", "chrome-rule": "#ce8798",
        "chrome-ink": "#36111c", "chrome-accent": "#8c0e46", accent: "#a70052", "accent-2": "#b12f61", link: "#006738",
        warn: "#ac3400", ok: "#137738", "good-border": "#88ca95", "good-bg": "#e8fbeb", "warn-border": "#e5b568",
        "warn-bg": "#fff4e4", "warn-ink": "#804810", "bar-fill": "#c32d69", "row-hover": "#ffe8ec",
      },
      dark: {
        paper: "#432029", "paper-2": "#371921", "paper-3": "#532934", plain: "#4a242e", "plain-soft": "#3e1d26",
        "page-paper": "#4c2731", "page-line": "#7d4453", ink: "#faf3f4", "ink-2": "#ecd8dc", "ink-3": "#d8bcc1",
        "ink-4": "#a28289", rule: "#8d4d5d", "rule-2": "#683643", chrome: "#5b2133", "chrome-rule": "#833f52",
        "chrome-ink": "#fceef0", "chrome-accent": "#ffc38f", accent: "#ff9bb7", "accent-2": "#fa82a6", link: "#8bdda8",
        warn: "#ff9d7f", ok: "#7fd994", "good-border": "#458554", "good-bg": "#102816", "warn-border": "#a17833",
        "warn-bg": "#2d1f05", "warn-ink": "#f9cc87", "bar-fill": "#fe7ea6", "row-hover": "#5a2d39",
      },
    },
  };
  // palettes:end

  function readStorage(key) {
    try {
      return window.localStorage.getItem(key);
    } catch {
      return null;
    }
  }

  function writeStorage(key, value) {
    try {
      window.localStorage.setItem(key, value);
    } catch {
      // Theme changes should remain usable when storage is unavailable.
    }
  }

  function viewerId() {
    const configured =
      root.dataset.amycViewer ||
      root.dataset.viewer ||
      document.body?.dataset.amycViewer ||
      document.body?.dataset.viewer ||
      document.querySelector("[data-amyc-viewer]")?.getAttribute("data-amyc-viewer") ||
      document.querySelector("[data-viewer-id]")?.getAttribute("data-viewer-id") ||
      location.pathname ||
      "default";
    const normalized = String(configured).trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
    return normalized || "default";
  }

  function scopedStorageKey(key) {
    return `amyc-viewer:${viewerId()}:${key}`;
  }

  function publicRecordsFooterSetting() {
    return String(
      root.dataset.amycPublicRecordsFooter ||
      document.body?.dataset.amycPublicRecordsFooter ||
      scriptEl?.dataset.amycPublicRecordsFooter ||
      "",
    ).trim().toLowerCase();
  }

  function publicRecordsFooterEnabled() {
    return !["0", "false", "off", "none", "hidden"].includes(publicRecordsFooterSetting());
  }

  function mountPublicRecordsFooter() {
    if (!document.body) {
      document.addEventListener("DOMContentLoaded", mountPublicRecordsFooter, { once: true });
      return;
    }
    if (!publicRecordsFooterEnabled()) return;
    if (document.querySelector(".amyc-public-records-footer")) return;

    const footer = document.createElement("footer");
    footer.className = "amyc-public-records-footer";
    footer.dataset.amycPublicRecordsFooter = "1";
    footer.setAttribute("role", "contentinfo");
    footer.setAttribute("aria-label", "Public records contact notice");
    footer.title = `${publicRecordsFooterPrefix}${publicRecordsFooterContact}.`;

    const text = document.createElement("span");
    text.textContent = publicRecordsFooterPrefix;

    const link = document.createElement("a");
    link.href = `mailto:${publicRecordsFooterContact}`;
    link.textContent = publicRecordsFooterContact;

    footer.append(text, link, document.createTextNode("."));
    document.body.appendChild(footer);
    document.body.classList.add("amyc-has-public-records-footer");
  }

  function syncAcrossViewers() {
    return readStorage(syncViewersKey) !== "0";
  }

  function activeStorageKey(key) {
    return syncAcrossViewers() ? key : scopedStorageKey(key);
  }

  function readPref(key) {
    if (syncAcrossViewers()) return readStorage(key);
    const scoped = readStorage(scopedStorageKey(key));
    return scoped == null ? readStorage(key) : scoped;
  }

  function writePref(key, value) {
    writeStorage(activeStorageKey(key), value);
  }

  function updatePersistenceControls() {
    const synced = syncAcrossViewers();
    document.querySelectorAll("[data-amyc-sync-viewers]").forEach((input) => {
      input.checked = synced;
      input.setAttribute("aria-checked", synced ? "true" : "false");
    });
  }

  function currentCustomCss() {
    return document.getElementById("amyc-custom-css")?.textContent || "";
  }

  function persistCurrentPrefs() {
    writePref(themeKey, root.dataset.theme || defaultThemeId);
    writePref(lightnessKey, String(currentLightness));
    writePref(customCssKey, currentCustomCss());
  }

  function setSyncAcrossViewers(enabled, source = "theme") {
    writeStorage(syncViewersKey, enabled ? "1" : "0");
    persistCurrentPrefs();
    updatePersistenceControls();
    window.dispatchEvent(new CustomEvent(storageEventName, {
      detail: { synced: enabled, source },
    }));
  }

  function normalizeTheme(value) {
    if (value === "dark") return "starlight";
    if (value === "light" || value === "docket") return defaultThemeId;
    return themes.some((theme) => theme.id === value) ? value : defaultThemeId;
  }

  function normalizeLightness(value) {
    const numeric = Number(value);
    if (!Number.isFinite(numeric)) return 0;
    return Math.max(-40, Math.min(40, Math.round(numeric)));
  }

  function selectedIndex() {
    const current = normalizeTheme(root.dataset.theme || readPref(themeKey));
    return Math.max(0, themes.findIndex((theme) => theme.id === current));
  }

  function defaultThemeIndex() {
    return Math.max(0, themes.findIndex((theme) => theme.id === defaultThemeId));
  }

  function activeTheme() {
    return themes[selectedIndex()] || themes[0];
  }

  function lightnessTone(value = currentLightness) {
    const normalized = normalizeLightness(value);
    if (normalized >= 31) return "lightest";
    if (normalized >= 11) return "lighter";
    if (normalized <= -31) return "darkest";
    if (normalized <= -11) return "darker";
    return "base";
  }

  function signedLightness(value = currentLightness) {
    const normalized = normalizeLightness(value);
    return normalized > 0 ? `+${normalized}` : String(normalized);
  }

  function themeDisplayName(theme = activeTheme(), value = currentLightness) {
    return theme.names?.[lightnessTone(value)] || theme.name;
  }

  function snapRangeToMarkers(input) {
    const points = String(input.dataset.snapPoints || "")
      .split(",")
      .map((point) => Number(point.trim()))
      .filter((point) => Number.isFinite(point));
    const threshold = Number(input.dataset.snapThreshold || 0);
    const value = Number(input.value);
    if (!points.length || !Number.isFinite(threshold) || !Number.isFinite(value)) return false;
    let nearest = points[0];
    let distance = Math.abs(value - nearest);
    for (const point of points.slice(1)) {
      const nextDistance = Math.abs(value - point);
      if (nextDistance < distance) {
        nearest = point;
        distance = nextDistance;
      }
    }
    if (distance > threshold) return false;
    input.value = String(nearest);
    return nearest !== value;
  }

  function updateThemeLabels(theme = activeTheme()) {
    const displayName = themeDisplayName(theme);
    const baseName = theme.name || displayName;
    const fullName = currentLightness && displayName !== baseName
      ? `${displayName} (${baseName} ${signedLightness()})`
      : `${displayName}${currentLightness ? ` ${signedLightness()}` : ""}`;
    root.dataset.themeTone = lightnessTone();
    document.querySelectorAll("[data-theme-toggle]").forEach((button) => {
      button.setAttribute("aria-label", `Theme spectrum: ${fullName}`);
      button.setAttribute("title", `Theme spectrum: ${fullName}`);
    });
    document.querySelectorAll("[data-theme-current]").forEach((node) => {
      node.textContent = displayName;
      node.setAttribute("title", fullName);
    });
  }

  function setCustomCss(cssText) {
    let style = document.getElementById("amyc-custom-css");
    if (!cssText.trim()) {
      if (style) style.remove();
      return;
    }
    if (!style) {
      style = document.createElement("style");
      style.id = "amyc-custom-css";
      document.head.appendChild(style);
    }
    style.textContent = cssText;
  }

  function resetThemePrefs() {
    currentLightness = defaultLightness;
    writePref(themeKey, defaultThemeId);
    writePref(lightnessKey, String(defaultLightness));
    applyTheme(defaultThemeId, false);
  }

  function parseColor(value) {
    const color = value.trim();
    const hex = color.match(/^#([0-9a-f]{3}|[0-9a-f]{6})$/i);
    if (hex) {
      const raw = hex[1].length === 3
        ? hex[1].split("").map((char) => `${char}${char}`).join("")
        : hex[1];
      return [0, 2, 4].map((index) => parseInt(raw.slice(index, index + 2), 16));
    }
    const rgb = color.match(/^rgba?\((\d+),\s*(\d+),\s*(\d+)/i);
    if (rgb) {
      return rgb.slice(1, 4).map((channel) => Number(channel));
    }
    return null;
  }

  function toRgb(color) {
    return `rgb(${color.map((channel) => Math.round(channel)).join(", ")})`;
  }

  function mixColor(color, target, amount) {
    return color.map((channel, index) => channel + (target[index] - channel) * amount);
  }

  function relativeLuminance(color) {
    const [r, g, b] = color.map((channel) => {
      const value = channel / 255;
      return value <= 0.03928 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4;
    });
    return 0.2126 * r + 0.7152 * g + 0.0722 * b;
  }

  function contrastRatio(a, b) {
    const light = Math.max(relativeLuminance(a), relativeLuminance(b));
    const dark = Math.min(relativeLuminance(a), relativeLuminance(b));
    return (light + 0.05) / (dark + 0.05);
  }

  function ensureContrast(color, background, minimum) {
    if (contrastRatio(color, background) >= minimum) return color;
    const darkTarget = [0, 0, 0];
    const lightTarget = [255, 255, 255];
    const target = contrastRatio(darkTarget, background) >= contrastRatio(lightTarget, background)
      ? darkTarget
      : lightTarget;
    let adjusted = color;
    for (let step = 0; step < 12 && contrastRatio(adjusted, background) < minimum; step += 1) {
      adjusted = mixColor(adjusted, target, 0.18);
    }
    return adjusted;
  }

  function ensureContrastAcross(color, backgrounds, minimum) {
    return backgrounds.reduce(
      (current, background) => ensureContrast(current, background, minimum),
      color,
    );
  }

  const derivedTokens = ["document-ink", "document-ink-2", "document-ink-3", "document-accent", "theme-color-scheme"];
  function clearAdjustedTokens() {
    [...adjustableTokens, ...derivedTokens].forEach((token) => root.style.removeProperty(`--${token}`));
  }

  // Custom CSS may set a base token in any CSS color syntax.
  let colorContext;
  function parseThemeColor(value) {
    const basic = parseColor(value);
    if (basic) return basic;
    if (!value.trim() || !CSS.supports("color", value)) return null;
    colorContext ||= document.createElement("canvas").getContext("2d", { willReadFrequently: true });
    colorContext.fillStyle = "#ffffff";
    colorContext.fillRect(0, 0, 1, 1);
    colorContext.fillStyle = value;
    colorContext.fillRect(0, 0, 1, 1);
    return Array.from(colorContext.getImageData(0, 0, 1, 1).data).slice(0, 3);
  }

  // Moves a color toward the text polarity only as far as every background needs.
  function ensureReadable(color, backgrounds, minimum, target) {
    const readable = (candidate) => backgrounds.every((background) => contrastRatio(candidate, background) >= minimum);
    if (readable(color)) return color;
    let low = 0;
    let high = 1;
    for (let step = 0; step < 16; step++) {
      const amount = (low + high) / 2;
      if (readable(mixColor(color, target, amount))) high = amount;
      else low = amount;
    }
    return mixColor(color, target, high);
  }

  // Blends base -> +/-20 -> +/-40, then enforces contrast for page text, the
  // consumer chart fills, and a masthead tinted with up to 24% accent.
  function applyLightness(value, persist) {
    currentLightness = normalizeLightness(value);
    if (persist) {
      writePref(lightnessKey, String(currentLightness));
    }

    clearAdjustedTokens();
    const direction = currentLightness > 0 ? "light" : "dark";
    const midpoint = themeMidpoints[root.dataset.theme][direction];
    const endpoint = themeVariants[root.dataset.theme][direction];
    const firstLeg = Math.abs(currentLightness) <= 20;
    const amount = firstLeg ? Math.abs(currentLightness) / 20 : (Math.abs(currentLightness) - 20) / 20;
    const adjusted = {};
    adjustableTokens.forEach((token) => {
      const base = parseThemeColor(baseThemeTokens[token] || "") || parseColor(midpoint[token] || "");
      const mid = parseColor(midpoint[token] || "") || base;
      const end = parseColor(endpoint[token] || "") || mid;
      if (base && mid && end) adjusted[token] = mixColor(firstLeg ? base : mid, firstLeg ? mid : end, amount);
    });
    const paper = adjusted.paper;
    const polarity = contrastRatio([0, 0, 0], paper) >= contrastRatio([255, 255, 255], paper) ? [0, 0, 0] : [255, 255, 255];
    const surfaceTarget = polarity[0] === 0 ? [255, 255, 255] : [0, 0, 0];
    const surfaceNames = ["paper", "paper-2", "paper-3", "plain", "plain-soft", "page-paper", "row-hover", "good-bg", "warn-bg"];
    surfaceNames.forEach((token) => {
      let color = adjusted[token];
      for (let i = 0; i < 100 && contrastRatio(polarity, color) < 5.3; i++) color = mixColor(color, surfaceTarget, 0.03);
      adjusted[token] = color.map(Math.round);
    });
    const seeds = { ...adjusted };
    const foregroundNames = ["ink", "ink-2", "ink-3", "accent", "accent-2", "link", "warn", "ok", "bar-fill", "warn-ink"];
    let surfaces;
    let diagramSurfaces;
    // A diagram can tint its surface with a chart color. Reserve enough
    // contrast for the same text polarity on both the page and those fills.
    const chartFills = (plain) => [
      mixColor(plain, adjusted.link, 0.36),
      mixColor(plain, adjusted["bar-fill"], 0.52),
      mixColor(plain, polarity, 0.26),
    ];
    const roomy = (fills) => fills.every((surface) => contrastRatio(polarity, surface) >= 4.8);
    for (let step = 0; step < 100; step++) {
      surfaces = surfaceNames.map((token) => adjusted[token]);
      foregroundNames.forEach((token) => {
        adjusted[token] = ensureReadable(seeds[token], surfaces, 4.6, polarity);
      });
      diagramSurfaces = [...surfaces, ...chartFills(adjusted.plain)];
      if (roomy(diagramSurfaces)) break;
      // Chart fills sit on --plain, so move it alone when that is enough and
      // keep the page's other surfaces as designed (or as custom CSS set them).
      if (roomy(chartFills(mixColor(adjusted.plain, surfaceTarget, 0.75)))) {
        let low = 0;
        let high = 0.75;
        for (let i = 0; i < 16; i++) {
          const amount = (low + high) / 2;
          if (roomy(chartFills(mixColor(adjusted.plain, surfaceTarget, amount)))) high = amount;
          else low = amount;
        }
        adjusted.plain = mixColor(adjusted.plain, surfaceTarget, high);
      } else {
        surfaceNames.forEach((token) => adjusted[token] = mixColor(adjusted[token], surfaceTarget, 0.04));
      }
    }
    ["ink", "ink-2", "ink-3"].forEach((token) => {
      adjusted[token] = ensureReadable(seeds[token], diagramSurfaces, 4.6, polarity);
    });
    // Mastheads may tint the header with 24% accent and render secondary
    // header text at 82% opacity. Imperial's header also crosses white to black.
    const headerSurfaces = () => Array.from({ length: 17 }, (_, i) => mixColor(adjusted.chrome, adjusted.accent, i * 0.015));
    const secondaryContrast = (color, backgrounds) => Math.min(...backgrounds.map((background) =>
      contrastRatio(mixColor(background, color, 0.82), background)));
    let backgrounds = headerSurfaces();
    const black = [0, 0, 0], white = [255, 255, 255];
    const headerInk = secondaryContrast(black, backgrounds) >= secondaryContrast(white, backgrounds) ? black : white;
    const headerTarget = headerInk[0] === 0 ? white : black;
    for (let step = 0; step < 100 && secondaryContrast(headerInk, backgrounds) < 4.8; step++) {
      adjusted.chrome = mixColor(adjusted.chrome, headerTarget, 0.04);
      backgrounds = headerSurfaces();
    }
    if (secondaryContrast(adjusted["chrome-ink"], backgrounds) < 4.6) {
      const seed = adjusted["chrome-ink"];
      let low = 0, high = 1;
      for (let step = 0; step < 16; step++) {
        const amount = (low + high) / 2;
        if (secondaryContrast(mixColor(seed, headerInk, amount), backgrounds) >= 4.6) high = amount;
        else low = amount;
      }
      adjusted["chrome-ink"] = mixColor(seed, headerInk, high);
    }
    adjusted["chrome-accent"] = ensureReadable(adjusted["chrome-accent"], backgrounds, 4.6, headerInk);
    ["good-border", "warn-border"].forEach((token) => {
      adjusted[token] = ensureReadable(adjusted[token], surfaces, 3.1, polarity);
    });
    Object.entries(adjusted).forEach(([token, color]) => root.style.setProperty(`--${token}`, toRgb(color)));
    const styles = getComputedStyle(root);
    const documentPaper = parseThemeColor(styles.getPropertyValue("--document-paper")) || adjusted["page-paper"];
    // Consumers can keep a document white inside a dark shell. Use the actual
    // surface as the document's text reference without changing that surface.
    const documentSoft = parseThemeColor(styles.getPropertyValue("--document-paper-soft")) || documentPaper;
    const documentSurfaces = [documentPaper, documentSoft];
    ["ink", "ink-2", "ink-3", "accent"].forEach((token) => {
      root.style.setProperty(`--document-${token}`, toRgb(ensureContrastAcross(adjusted[token], documentSurfaces, 4.6)));
    });
    root.style.setProperty("--theme-color-scheme", polarity[0] === 0 ? "light" : "dark");
    if (metaTheme) metaTheme.setAttribute("content", toRgb(adjusted.chrome));
    document.querySelectorAll("[data-theme-lightness]").forEach((input) => input.value = String(currentLightness));
    document.querySelectorAll("[data-lightness-value]").forEach((node) => node.textContent = signedLightness());
    updateThemeLabels();
  }

  function collectBaseTokens() {
    const styles = getComputedStyle(root);
    baseThemeTokens = {};
    adjustableTokens.forEach((token) => {
      baseThemeTokens[token] = styles.getPropertyValue(`--${token}`).trim();
    });
  }

  function applyTheme(themeId, persist) {
    const theme = themes.find((item) => item.id === themeId) || themes[0];
    clearAdjustedTokens();
    root.dataset.theme = theme.id;
    collectBaseTokens();
    if (persist) {
      writePref(themeKey, theme.id);
    }
    document.querySelectorAll("[data-theme-spectrum]").forEach((input) => {
      input.value = String(themes.indexOf(theme));
    });
    document.querySelectorAll("[data-theme-choice]").forEach((button) => {
      button.setAttribute("aria-pressed", button.dataset.themeChoice === theme.id ? "true" : "false");
    });
    applyLightness(currentLightness, false);
  }

  function makeSwatch(theme) {
    const swatch = document.createElement("span");
    swatch.className = "theme-swatch";
    swatch.style.setProperty("--swatch-chrome", theme.colors[0]);
    swatch.style.setProperty("--swatch-paper-2", theme.colors[1]);
    swatch.style.setProperty("--swatch-accent", theme.colors[2]);
    swatch.style.setProperty("--swatch-plain", theme.colors[3]);
    swatch.style.setProperty("--swatch-rule", theme.colors[0]);
    for (let index = 0; index < 4; index += 1) {
      swatch.appendChild(document.createElement("span"));
    }
    return swatch;
  }

  function buildPanel(toggle, panelId) {
    const panel = document.createElement("div");
    panel.className = "theme-panel";
    panel.id = panelId;
    panel.hidden = true;
    panel.innerHTML = `
      <div class="theme-panel-head">
        <span>Theme</span>
        <span data-theme-current></span>
      </div>
      <div class="theme-control-grid">
        <div class="lightness-control">
          <span class="lightness-endpoint is-light" title="Light" aria-hidden="true"></span>
          <span class="lightness-slider-wrap amyc-snap-track is-vertical" style="--snap-default: 50%;">
            <span class="amyc-snap amyc-snap-min" aria-hidden="true"></span>
            <span class="amyc-snap amyc-snap-default" aria-hidden="true"></span>
            <span class="amyc-snap amyc-snap-max" aria-hidden="true"></span>
            <input class="lightness-input" type="range" min="-40" max="40" step="1" data-theme-lightness data-snap-points="-40,0,40" data-snap-threshold="1" aria-label="Theme lightness">
          </span>
          <span class="lightness-endpoint is-dark" title="Dark" aria-hidden="true"></span>
          <span class="lightness-value" data-lightness-value>0</span>
        </div>
        <div class="theme-spectrum">
          <div class="theme-spectrum-row amyc-snap-track" style="--snap-default: ${(defaultThemeIndex() / (themes.length - 1)) * 100}%;">
            <span class="amyc-snap amyc-snap-min" aria-hidden="true"></span>
            <span class="amyc-snap amyc-snap-default" aria-hidden="true"></span>
            <span class="amyc-snap amyc-snap-max" aria-hidden="true"></span>
            <input class="theme-spectrum-input" type="range" min="0" max="${themes.length - 1}" step="1" data-theme-spectrum data-snap-points="0,${defaultThemeIndex()},${themes.length - 1}" aria-label="Theme spectrum">
          </div>
          <div class="theme-options" data-theme-options></div>
        </div>
      </div>
      <div class="theme-actions">
        <button class="hbtn" type="button" data-theme-reset>Reset theme</button>
        <button class="theme-persistence-toggle" type="button" role="switch" aria-checked="true" data-amyc-sync-viewers title="Share theme and font settings across AMYC viewers">
          <span class="theme-sync-knob" aria-hidden="true"></span>
          <span>Sync viewers</span>
        </button>
      </div>
      <details class="custom-css-box" data-custom-css-box>
        <summary class="custom-css-summary">
          <span>Custom CSS</span>
          <span class="custom-css-status" data-custom-css-status></span>
        </summary>
        <div class="custom-css-body">
          <textarea class="custom-css-input" id="${panelId}-css" data-custom-css spellcheck="false" aria-label="Custom CSS"></textarea>
          <div class="custom-css-actions">
            <button class="hbtn" type="button" data-custom-css-apply>Apply CSS</button>
            <button class="hbtn" type="button" data-custom-css-reset>Reset CSS</button>
          </div>
        </div>
      </details>
    `;

    const options = panel.querySelector("[data-theme-options]");
    themes.forEach((theme) => {
      const button = document.createElement("button");
      button.className = "theme-choice";
      button.type = "button";
      button.dataset.themeChoice = theme.id;
      button.appendChild(makeSwatch(theme));

      const copy = document.createElement("span");
      const name = document.createElement("span");
      const note = document.createElement("span");
      name.className = "theme-name";
      note.className = "theme-note";
      name.textContent = theme.name;
      note.textContent = theme.note;
      copy.append(name, note);
      button.appendChild(copy);
      button.addEventListener("click", () => {
        applyTheme(theme.id, true);
      });
      options.appendChild(button);
    });

    const spectrum = panel.querySelector("[data-theme-spectrum]");
    const lightness = panel.querySelector("[data-theme-lightness]");
    spectrum.addEventListener("input", () => {
      snapRangeToMarkers(spectrum);
      const theme = themes[Number(spectrum.value)] || themes[0];
      applyTheme(theme.id, true);
      const active = panel.querySelector(`[data-theme-choice="${theme.id}"]`);
      if (active) {
        active.scrollIntoView({ block: "nearest", inline: "nearest" });
      }
    });
    lightness.addEventListener("input", () => {
      applyLightness(lightness.value, true);
    });
    lightness.addEventListener("change", () => {
      if (snapRangeToMarkers(lightness)) {
        applyLightness(lightness.value, true);
      }
    });
    panel.querySelector("[data-theme-reset]").addEventListener("click", () => {
      resetThemePrefs();
    });
    panel.querySelector("[data-amyc-sync-viewers]").addEventListener("click", (event) => {
      setSyncAcrossViewers(event.currentTarget.getAttribute("aria-checked") !== "true", "theme");
    });

    const cssInput = panel.querySelector("[data-custom-css]");
    const cssStatus = panel.querySelector("[data-custom-css-status]");
    cssInput.value = readPref(customCssKey) || "";
    panel.querySelector("[data-custom-css-box]").open = !!cssInput.value.trim();
    panel.querySelector("[data-custom-css-apply]").addEventListener("click", () => {
      const value = cssInput.value;
      setCustomCss(value);
      writePref(customCssKey, value);
      applyTheme(root.dataset.theme, false);
      cssStatus.textContent = value.trim() ? "Custom CSS applied" : "Custom CSS cleared";
    });
    panel.querySelector("[data-custom-css-reset]").addEventListener("click", () => {
      cssInput.value = "";
      setCustomCss("");
      writePref(customCssKey, "");
      applyTheme(root.dataset.theme, false);
      cssStatus.textContent = "Custom CSS cleared";
    });

    toggle.after(panel);
    return panel;
  }

  const storedTheme = normalizeTheme(readPref(themeKey));
  currentLightness = normalizeLightness(readPref(lightnessKey));
  const storedCss = readPref(customCssKey) || "";
  applyTheme(storedTheme, false);
  setCustomCss(storedCss);

  document.querySelectorAll("[data-theme-toggle]").forEach((toggle, index) => {
    const panel = buildPanel(toggle, `theme-panel-${index}`);
    toggle.setAttribute("aria-haspopup", "dialog");
    toggle.setAttribute("aria-expanded", "false");
    toggle.setAttribute("aria-controls", panel.id);

    toggle.addEventListener("click", () => {
      const willOpen = panel.hidden;
      document.querySelectorAll(".theme-panel").forEach((otherPanel) => {
        otherPanel.hidden = true;
      });
      document.querySelectorAll("[data-theme-toggle]").forEach((otherToggle) => {
        otherToggle.setAttribute("aria-expanded", "false");
      });
      panel.hidden = !willOpen;
      toggle.setAttribute("aria-expanded", willOpen ? "true" : "false");
      if (willOpen) {
        const input = panel.querySelector("[data-theme-spectrum]");
        if (input) input.focus();
      }
    });
  });

  document.addEventListener("click", (event) => {
    if (event.target.closest(".theme-panel") || event.target.closest("[data-theme-toggle]")) return;
    document.querySelectorAll(".theme-panel").forEach((panel) => {
      panel.hidden = true;
    });
    document.querySelectorAll("[data-theme-toggle]").forEach((toggle) => {
      toggle.setAttribute("aria-expanded", "false");
    });
  });

  document.addEventListener("keydown", (event) => {
    if (event.key !== "Escape") return;
    document.querySelectorAll(".theme-panel").forEach((panel) => {
      panel.hidden = true;
    });
    document.querySelectorAll("[data-theme-toggle]").forEach((toggle) => {
      toggle.setAttribute("aria-expanded", "false");
    });
  });

  window.addEventListener(storageEventName, (event) => {
    if (event.detail?.source === "theme") return;
    persistCurrentPrefs();
    updatePersistenceControls();
  });

  updatePersistenceControls();
  applyTheme(themes[selectedIndex()].id, false);
  mountPublicRecordsFooter();
})();
